# -*- mode: Makefile -*-
# -*- eval: (outline-minor-mode); outline-regexp: "# [*]+"; -*-

PACKAGE_VERSION=2.30.1
PACKAGE_URL=https://mirrors.edge.kernel.org/pub/software/scm/git
PACKAGE_ARCHIVE_DIR=$(PACKAGE_DIR)/git-$(PACKAGE_VERSION)

LOCAL_TARGET_PATH=bin/git
ARCHIVE_TARGET_PATH=git
