# -*- mode: Makefile -*-
# -*- eval: (outline-minor-mode); outline-regexp: "# [*]+"; -*-

# This file defines the variables needed to retrieve, build and install curl.

PACKAGE_VERSION=2.1.0
PACKAGE_URL=https://github.com/remotemobprogramming/mob/releases/download/v$(PACKAGE_VERSION)/mob_v$(PACKAGE_VERSION)_linux_amd64.tar.gz
PACKAGE_TYPE=uncompress-copy
# the archive doesn't have a root directory
# PACKAGE_ARCHIVE_DIR=
PACKAGE_ARCHIVE_TARGET=mob
PACKAGE_STOW_TARGET=bin/mob
