# -*- mode: Makefile -*-
# -*- eval: (outline-minor-mode); outline-regexp: "# [*]+"; -*-

PACKAGE_VERSION=2.30.1
PACKAGE_NAME_VERSION=git-$(PACKAGE_VERSION)
PACKAGE_STOW_DIR=$(STOW_DIR)/$(PACKAGE_NAME_VERSION)
PACKAGE_ARCHIVE_DIR=$(PACKAGE_DIR)/git-$(PACKAGE_VERSION)
PACKAGE_ARCHIVE=git-$(PACKAGE_VERSION).tar.gz
PACKAGE_URL=https://mirrors.edge.kernel.org/pub/software/scm/git
LOCAL_TARGET_PATH=bin/git

ARCHIVE_TARGET_PATH=git
