# -*- mode: Makefile -*-
# -*- eval: (outline-minor-mode); outline-regexp: "# [*]+"; -*-

PACKAGE_VERSION=2.30.1
PACKAGE_URL=https://mirrors.edge.kernel.org/pub/software/scm/git/git-$(PACKAGE_VERSION).tar.gz
PACKAGE_ARCHIVE_DIR=git-$(PACKAGE_VERSION)
PACKAGE_ARCHIVE_TARGET=git
PACKAGE_STOW_TARGET=bin/git
