# -*- mode: Makefile -*-
# -*- eval: (outline-minor-mode); outline-regexp: "# [*]+"; -*-

# The next target also updates the timestamp of the target file, which is one of
# the uncompressed files. In this way the archive is only uncompressed once as
# the timestamp of the archive is older.

$(PACKAGE_ARCHIVE_PATH)/configure: $(WORKBENCH_PATH)/$(PACKAGE_ARCHIVE)
	# Uncompress $(PACKAGE) source package
	$(PACKAGE_UNCOMPRESS_COMMAND)
	@touch $@
